// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bids.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createdBid = `-- name: CreatedBid :one
INSERT INTO bids(
  product_id, bidder_id, bid_amount_in_cents
) VALUES ($1, $2, $3)
RETURNING id, product_id, bidder_id, bid_amount_in_cents, created_at
`

type CreatedBidParams struct {
	ProductID        uuid.UUID `json:"product_id"`
	BidderID         uuid.UUID `json:"bidder_id"`
	BidAmountInCents int32     `json:"bid_amount_in_cents"`
}

func (q *Queries) CreatedBid(ctx context.Context, arg CreatedBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createdBid, arg.ProductID, arg.BidderID, arg.BidAmountInCents)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.BidAmountInCents,
		&i.CreatedAt,
	)
	return i, err
}

const getBidsByProductId = `-- name: GetBidsByProductId :many
SELECT id, product_id, bidder_id, bid_amount_in_cents, created_at FROM bids
WHERE product_id = $1
ORDER BY bid_amount_in_cents DESC
`

func (q *Queries) GetBidsByProductId(ctx context.Context, productID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByProductId, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BidderID,
			&i.BidAmountInCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBidByProductId = `-- name: GetHighestBidByProductId :one
SELECT id, product_id, bidder_id, bid_amount_in_cents, created_at FROM bids
WHERE product_id = $1
ORDER BY bid_amount_in_cents DESC
LIMIT 1
`

func (q *Queries) GetHighestBidByProductId(ctx context.Context, productID uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getHighestBidByProductId, productID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.BidAmountInCents,
		&i.CreatedAt,
	)
	return i, err
}
